"""removed_uniques_constraints

Revision ID: 0e8b05e72054
Revises: 83a522c538ca
Create Date: 2023-12-01 11:10:55.752168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8b05e72054'
down_revision: Union[str, None] = '83a522c538ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_groups_group_name_key', 'task_groups', type_='unique')
    op.drop_constraint('tasks_title_key', 'tasks', type_='unique')
    op.drop_constraint('user_groups_group_name_key', 'user_groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_groups_group_name_key', 'user_groups', ['group_name'])
    op.create_unique_constraint('tasks_title_key', 'tasks', ['title'])
    op.create_unique_constraint('task_groups_group_name_key', 'task_groups', ['group_name'])
    # ### end Alembic commands ###
