"""task group assignments

Revision ID: 23fe895b5c5b
Revises: 973687520b5d
Create Date: 2023-12-02 16:16:18.478963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fe895b5c5b'
down_revision: Union[str, None] = '973687520b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups_task_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups_task_groups',
    sa.Column('user_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_group_id'], ['task_groups.id'], name='user_groups_task_groups_task_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name='user_groups_task_groups_user_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_group_id', 'task_group_id', name='user_groups_task_groups_pkey')
    )
    # ### end Alembic commands ###
