"""uniqueConstraints

Revision ID: 973687520b5d
Revises: 0e8b05e72054
Create Date: 2023-12-01 15:49:43.454918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973687520b5d'
down_revision: Union[str, None] = '0e8b05e72054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task_groups', ['group_owner_id', 'group_name'])
    op.create_unique_constraint(None, 'tasks', ['task_owner_id', 'title'])
    op.create_unique_constraint(None, 'user_groups', ['group_owner_id', 'group_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'task_groups', type_='unique')
    # ### end Alembic commands ###
